[project]
name = 'project_euromir'
version = '0.0.1'
readme = 'README.md'
requires-python = '>=3.8'
license = {file = 'LICENSE'}
authors = [{name = 'Enzo Busseti', email = 'enzo.busseti@gmail.com'}]
dependencies = ['numpy', 'scipy']

[project.optional-dependencies]
docs = ["sphinx"]
dev = [
    "build", "twine", "pylint", "isort", "autopep8", "docformatter", "numpy",
    "scipy"]

[build-system]
requires = ["setuptools", "cmake"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["project_euromir", "project_euromir.tests"]