name: Test

on:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  pylint:

  packaging:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12' 

      - name: Package
        run: |
              python -m pip install build
              python -m build

      - name: Install wheel
        run: |
              python -m pip install dist/*.whl

      - name: Delete the repo
        run: |
              rm -rf *
      
      - name: Run tests shipped with the package
        run: |
              python -m project_euromir.tests
