name: Test

# env:
#   # https://github.com/actions/runner-images
#   # last 2 are aarch64 and amd64
#   OSS: [ubuntu-latest, windows-latest, macos-latest, macos-13]

on:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  pip_editable_install:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:  [ubuntu-latest, windows-latest, macos-latest, macos-13]

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install libraries # f2c, temporary
        run:  |
              if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt install f2c -y
              elif [ "$RUNNER_OS" == "macOS" ]; then
                brew install f2c
              fi

      - name: Editable install
        run: python -m pip install -v -e .[test]

      - name: Test
        run: python -m project_euromir.tests

#
# not yet, needs a bunch of fixes to work in GH (windows doesn't recognize
# rm -rf, ...)
# 

  # pip_install:

  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest, macos-13]

  #   steps:

  #     - uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #           python-version: '3.11'

  #     - name: Pip install and remove repo
  #       run: |
  #             python -m pip install -v .
  #             rm -rf *

  #     - name: Test
  #       run: python -m project_euromir.tests

  # wheel_install:

  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest, macos-13]

  #   steps:

  #     - uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #           python-version: '3.11'

  #     - name: Create wheel, install, and remove repo
  #       run: |
  #             python -m pip install setuptools build wheel
  #             make pybuild # does also renaming of the wheel, needed for CIBuildWheel
  #             pip install dist/*.whl
  #             rm -rf *

  #     - name: Test
  #       run: python -m project_euromir.tests