name: Test

on:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  testing:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix: # https://github.com/actions/runner-images
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13] # last 2 are aarch64 and amd64

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Test using makefile
        run: make test
